#!/bin/bash

set -euo pipefail

rust-musl-builder() {
    docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly "$@"
}

rust-musl-builder cargo build --release
cp target/x86_64-unknown-linux-musl/release/brdgme-api deploy/app/brdgme-api
cd deploy
rm -f deploy.zip
zip -r deploy.zip *
cd -