#!/bin/bash

set -euo pipefail

docker run --rm -it -v "$(pwd)":/volume clux/muslrust cargo build --release
cp target/x86_64-unknown-linux-musl/release/brdgme-api deploy/brdgme-api
cd deploy
rm -f deploy.zip
zip -r deploy.zip *
cd -