[package]
name = "brdgme-api"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { git = "https://github.com/brdgme/std.git" }
brdgme-db = { git = "https://github.com/brdgme/db.git" }
lazy_static = "*"
error-chain = "*"
postgres = { version = "*", features=["with-uuid", "with-chrono"] }
rand = "*"
chrono = "*"
lettre = "*"
env_logger = "*"
rustless = "0.10.0"
iron = "0.4.0"
valico = "1.0.1"
email = "0.0.16"