[package]
name = "brdgme-api"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { git = "https://github.com/brdgme/std.git" }
brdgme-cmd = { git = "https://github.com/brdgme/cmd.git" }
brdgme-game = { git = "https://github.com/brdgme/game.git" }
brdgme-color = { git = "https://github.com/brdgme/color.git" }
lazy_static = "*"
error-chain = "*"
postgres = { version = "*", features = ["with-uuid", "with-chrono", "with-serde_json"] }
postgres-derive = "*"
r2d2 = "*"
r2d2_postgres = "*"
rand = "*"
chrono = "*"
lettre = "*"
log = "*"
env_logger = "*"
uuid = { version = "*", features = ["serde"] }
serde_json = "*"
rustless = "0.10.0"
iron = "0.4.0"
valico = "1.0.1"
email = "0.0.16"
hyper = "0.10.6"
hyper-native-tls = "0.2.2"